# =============================================================================
# Conformance with the Absolute engineering standard
# =============================================================================
# See https://github.com/abspwgm/.github
# =============================================================================

name: Conformance

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  conformance:
    name: Conformance
    uses: ./.github/workflows/conformance.yml
    with:
      standard-ref: fb8ff70ecd01e6e6f23291d442d69f310ded08f6
